src/Entity/Meeting.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MeetingRepository")
 */
class Meeting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $event_date;

    /**
     * @ORM\Column(type="date")
     */
    private $created_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MeetingParticipant", mappedBy="meeting_id", orphanRemoval=true)
     */
    private $meetingParticipants;

    public function __construct()
    {
        $this->meetingParticipants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->event_date;
    }

    public function setEventDate(\DateTimeInterface $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Collection|MeetingParticipant[]
     */
    public function getMeetingParticipants(): Collection
    {
        return $this->meetingParticipants;
    }

    public function addYe(MeetingParticipant $meetingParticipant): self
    {
        if (!$this->meetingParticipants->contains($meetingParticipant)) {
            $this->meetingParticipants[] = $meetingParticipant;
            $meetingParticipant->setMeetingId($this);
        }

        return $this;
    }

    public function removeMeetingParticipant(MeetingParticipant $meetingParticipant): self
    {
        if ($this->meetingParticipants->contains($meetingParticipant)) {
            $this->meetingParticipants->removeElement($meetingParticipant);
            // set the owning side to null (unless already changed)
            if ($meetingParticipant->getMeetingId() === $this) {
                $meetingParticipant->setMeetingId(null);
            }
        }

        return $this;
    }
}

src/Controller/MeetingController.php
<?php

namespace App\Controller;

use App\Entity\Meeting;
use Doctrine\DBAL\Types\TextType;
use http\Env\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MeetingController extends AbstractController
{
    /**
     * @Route("/meeting", name="meeting")
     */
    public function index()
    {
        $meetings = $this->getDoctrine()
            ->getRepository(Meeting::class)
            ->findAll([], []);
        return $this->render('meeting/index.html.twig', [
            'controller_name' => 'MeetingController',
            'meetings' => $meetings
        ]);
    }

    /**
     * @Route("/meeting/{id}", name="single_meeting")
     */
    public function show($id){
        $meeting = $this->getDoctrine()
            ->getRepository(Meeting::class)
            ->find($id);

        return $this->render('meeting/show.html.twig', ['m' =>$meeting]);
    }


    /**
     * @Route ("/meeting/new", name="new_meeting")
     * Method ({"GET", "POST"})
     */
    public function new(\Symfony\Component\HttpFoundation\Request $request) {
        $meeting = new Meeting();
        $form = $this->createFormBuilder($meeting)
            ->add('name', TextType::class, array('attr' =>array('class' => 'form-control')))
            ->add('eventDate', TextType::class, array('attr' =>array('class' => 'form-control')))
            ->add('createDate', TextType::class, array('attr' =>array('class' => 'form-control')))
            ->add('address', TextType::class, array('attr' =>array('class' => 'form-control')))
            ->add('save', SubmitType::class, array(
                'label' =>'Create',
                'attr' =>array('class'=>'btn btn-primary mt-3')
            ))
            ->getForm();

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $meeting = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($meeting);
            $entityManager->flush();
            return $this->redirectToRoute('meeting');
        }
        return $this->render('meeting/new.html.twig',array(
            'form'=>$form->createView()
        ));
    }

}

templates/meeting/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MeetingController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <ul>
        <ul>
            {% for m in meetings %}
                <li>
                    <strong>Name</strong>: {{ m.name }},
                    <strong>Event date</strong>: {{ m.eventDate|date('Y-m-d H:i:s') }},
                    <strong>Create date</strong>: {{ m.createdDate|date('Y-m-d H:i:s') }},
                    <strong>Address</strong>: {{ m.address }}
                    <div>
                        <h2>Participants:</h2>
                        <ul>
                            {% for p in m.meetingParticipants %}
                                {{ p.name}}
                            {% endfor %}
                        </ul>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </ul>
</div>
{% endblock %}

templates/meeting/new.html.twig
{% extends 'base.html.twig' %}

{% block title%}New Meeting {% endblock %}

{% block body %}

    <h1>New meeting</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end (form) }}

{% endblock %}

templates/meeting/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MeetingController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <ul>
        <ul>
            <li>
                <strong>Name</strong>: {{ m.name }},
                <strong>Event date</strong>: {{ m.eventDate|date('Y-m-d H:i:s') }},
                <strong>Create date</strong>: {{ m.createdDate|date('Y-m-d H:i:s') }},
                <strong>Address</strong>: {{ m.address }}
                <div>
                    <h2>Participants:</h2>
                    <ul>
                        {% for p in m.meetingParticipants %}
                            {{ p.name}}
                        {% endfor %}
                    </ul>
                </div>
            </li>
        </ul>
    </ul>
</div>
{% endblock %}